//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcde.Mobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("abcde.Mobile.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Verification.
        /// </summary>
        public static string Confirm_Verification {
            get {
                return ResourceManager.GetString("Confirm Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficult.
        /// </summary>
        public static string Difficult {
            get {
                return ResourceManager.GetString("Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID.
        /// </summary>
        public static string Email_ID {
            get {
                return ResourceManager.GetString("Email ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code which you have received from Email to change the password.
        /// </summary>
        public static string Enter_verification_code_which_you_have_received_from_Email_to_change_the_password {
            get {
                return ResourceManager.GetString("Enter verification code which you have received from Email to change the password" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Saving Prioritized Tasks.
        /// </summary>
        public static string ErrorWhileSavingPrioritizedTasks {
            get {
                return ResourceManager.GetString("ErrorWhileSavingPrioritizedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPassword?.
        /// </summary>
        public static string ForgotPassword_ {
            get {
                return ResourceManager.GetString("ForgotPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Added successfully.
        /// </summary>
        public static string Goal_Added_successfully {
            get {
                return ResourceManager.GetString("Goal Added successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Goal title.
        /// </summary>
        public static string Goal_Title_Required {
            get {
                return ResourceManager.GetString("Goal Title Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Updated successfully.
        /// </summary>
        public static string Goal_Updated_successfully {
            get {
                return ResourceManager.GetString("Goal Updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Title should at least two words.
        /// </summary>
        public static string GoalTitleShouldMinimumTwoWords {
            get {
                return ResourceManager.GetString("GoalTitleShouldMinimumTwoWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have to do.
        /// </summary>
        public static string HaveToDo {
            get {
                return ResourceManager.GetString("HaveToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Important is this ?  : .
        /// </summary>
        public static string How_Important_is_this {
            get {
                return ResourceManager.GetString("How Important is this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Urgent is this ?  : .
        /// </summary>
        public static string How_Urgent_is_this {
            get {
                return ResourceManager.GetString("How Urgent is this", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Have ToDo.
        /// </summary>
        public static string IHaveToDo {
            get {
                return ResourceManager.GetString("IHaveToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate.
        /// </summary>
        public static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string InitSetUpNext {
            get {
                return ResourceManager.GetString("InitSetUpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Want ToDo.
        /// </summary>
        public static string IWantToDo {
            get {
                return ResourceManager.GetString("IWantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Specific Deadline.
        /// </summary>
        public static string No_Specific_Deadline {
            get {
                return ResourceManager.GetString("No Specific Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Important.
        /// </summary>
        public static string Not_Important {
            get {
                return ResourceManager.GetString("Not Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified.
        /// </summary>
        public static string Not_Specified {
            get {
                return ResourceManager.GetString("Not Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string Old_Password {
            get {
                return ResourceManager.GetString("Old Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only four work items can be prioritized for a day.
        /// </summary>
        public static string OnlyFourWorkItemsCanBePrioritized {
            get {
                return ResourceManager.GetString("OnlyFourWorkItemsCanBePrioritized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation Code.
        /// </summary>
        public static string OrgCode {
            get {
                return ResourceManager.GetString("OrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target End Date &amp; Time.
        /// </summary>
        public static string OriginalEndDate {
            get {
                return ResourceManager.GetString("OriginalEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Continue to login.
        /// </summary>
        public static string Please_Continue_to_login {
            get {
                return ResourceManager.GetString("Please Continue to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid Credentials.
        /// </summary>
        public static string Please_enter_valid_Credentials {
            get {
                return ResourceManager.GetString("Please enter valid Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a future date.
        /// </summary>
        public static string Please_select_a_future_date {
            get {
                return ResourceManager.GetString("Please select a future date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prioritized Tasks Saved Successfully.
        /// </summary>
        public static string PrioritizedTasksSavedSuccessfully {
            get {
                return ResourceManager.GetString("PrioritizedTasksSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string Send_Email {
            get {
                return ResourceManager.GetString("Send Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we kindly ask all users to update their password during their initial login. Please take a moment to set a new password..
        /// </summary>
        public static string set_a_new_password_ {
            get {
                return ResourceManager.GetString("set a new password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTasks.
        /// </summary>
        public static string SubTasks {
            get {
                return ResourceManager.GetString("SubTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target end date is required.
        /// </summary>
        public static string Target_end_date_is_required {
            get {
                return ResourceManager.GetString("Target end date is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks completed.
        /// </summary>
        public static string tasks_completed {
            get {
                return ResourceManager.GetString("tasks completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string This_Week {
            get {
                return ResourceManager.GetString("This Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Pinned status successful.
        /// </summary>
        public static string UpdatedIsPinnedStatus {
            get {
                return ResourceManager.GetString("UpdatedIsPinnedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Less words in Title or Description.
        /// </summary>
        public static string Use_Less_words_in_Title_or_Description {
            get {
                return ResourceManager.GetString("Use Less words in Title or Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string User_Profile {
            get {
                return ResourceManager.GetString("User Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to do.
        /// </summary>
        public static string WantToDo {
            get {
                return ResourceManager.GetString("WantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you the link to the Email which you have entered below to change the password.
        /// </summary>
        public static string We_will_send_you_the_link_to_the_Email_which_you_have_entered_below_to_change_the_password {
            get {
                return ResourceManager.GetString("We will send you the link to the Email which you have entered below to change the" +
                        " password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Discipli App..
        /// </summary>
        public static string WelcomeToDiscipli {
            get {
                return ResourceManager.GetString("WelcomeToDiscipli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the org code given by your organisation here. If no special code given please leave it balnk and click Next..
        /// </summary>
        public static string WelcomInitialSetUpExplainer {
            get {
                return ResourceManager.GetString("WelcomInitialSetUpExplainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item not found.
        /// </summary>
        public static string WorkItemNotFound {
            get {
                return ResourceManager.GetString("WorkItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now change the password and login with the new password.
        /// </summary>
        public static string You_can_now_change_the_password_and_login_with_the_new_password {
            get {
                return ResourceManager.GetString("You can now change the password and login with the new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Only Pin Three Goals.
        /// </summary>
        public static string YouCanOnlyPin3WorkItems {
            get {
                return ResourceManager.GetString("YouCanOnlyPin3WorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can plan your day only before 12:00 PM.
        /// </summary>
        public static string YouCanPlanYourDayOnlyBefore12PM {
            get {
                return ResourceManager.GetString("YouCanPlanYourDayOnlyBefore12PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has updated, you can now login with the new password.
        /// </summary>
        public static string Your_password_has_updated__you_can_now_login_with_the_new_password {
            get {
                return ResourceManager.GetString("Your password has updated, you can now login with the new password", resourceCulture);
            }
        }
    }
}
