//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace abcde.Mobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("abcde.Mobile.Resx.AppResources_de", typeof(AppResources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Zurück.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de-Passwort ändern.
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Passwort bestätigen.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Bestätigen der Uberprufung.
        /// </summary>
        internal static string Confirm_Verification {
            get {
                return ResourceManager.GetString("Confirm Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Beschreibung.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Schwierig.
        /// </summary>
        internal static string Difficult {
            get {
                return ResourceManager.GetString("Difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Schwierigkeit.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Einfach.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_E-Mail-Identifikation.
        /// </summary>
        internal static string Email_ID {
            get {
                return ResourceManager.GetString("Email ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Geben Sie den Verifizierungscode ein, den Sie per E-Mail erhalten haben, um das Passwort zu ändern.
        /// </summary>
        internal static string Enter_verification_code_which_you_have_received_from_Email_to_change_the_password {
            get {
                return ResourceManager.GetString("Enter verification code which you have received from Email to change the password" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Passwort vergessen?.
        /// </summary>
        internal static string ForgotPassword_ {
            get {
                return ResourceManager.GetString("ForgotPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ziel erfolgreich hinzugefügt.
        /// </summary>
        internal static string Goal_Added_successfully {
            get {
                return ResourceManager.GetString("Goal Added successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ziel-Titel erforderlich.
        /// </summary>
        internal static string Goal_Title_Required {
            get {
                return ResourceManager.GetString("Goal Title Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ziel erfolgreich aktualisiert.
        /// </summary>
        internal static string Goal_Updated_successfully {
            get {
                return ResourceManager.GetString("Goal Updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ziel-Titel sollte mindestens zwei Wörter enthalten.
        /// </summary>
        internal static string GoalTitleShouldMinimumTwoWords {
            get {
                return ResourceManager.GetString("GoalTitleShouldMinimumTwoWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Erledigen.
        /// </summary>
        internal static string HaveToDo {
            get {
                return ResourceManager.GetString("HaveToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Hoch.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Wie wichtig ist dies ? :.
        /// </summary>
        internal static string How_Important_is_this____ {
            get {
                return ResourceManager.GetString("How Important is this ? :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Wie dringend ist dies ? :.
        /// </summary>
        internal static string How_Urgent_is_this____ {
            get {
                return ResourceManager.GetString("How Urgent is this ? :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ich möchte tun.
        /// </summary>
        internal static string IHaveToDo {
            get {
                return ResourceManager.GetString("IHaveToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Unmittelbar.
        /// </summary>
        internal static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Wichtig.
        /// </summary>
        internal static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Initialisierungseinrichtung Nächste.
        /// </summary>
        internal static string InitSetUpNext {
            get {
                return ResourceManager.GetString("InitSetUpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ich möchte tun.
        /// </summary>
        internal static string IWantToDo {
            get {
                return ResourceManager.GetString("IWantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_später.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Anmelden.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Abmelden.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_niedrig.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Mittel.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Neu.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Neues Passwort.
        /// </summary>
        internal static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_ Nächste.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Keine spezifische Frist.
        /// </summary>
        internal static string No_Specific_Deadline {
            get {
                return ResourceManager.GetString("No Specific Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Nicht wichtig.
        /// </summary>
        internal static string Not_Important {
            get {
                return ResourceManager.GetString("Not Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Nicht spezifiziert.
        /// </summary>
        internal static string Not_Specified {
            get {
                return ResourceManager.GetString("Not Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Notizenseite.
        /// </summary>
        internal static string Notes_Page {
            get {
                return ResourceManager.GetString("Notes Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_In Ordnung.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Altes Passwort.
        /// </summary>
        internal static string Old_Password {
            get {
                return ResourceManager.GetString("Old Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Organisationscode.
        /// </summary>
        internal static string OrgCode {
            get {
                return ResourceManager.GetString("OrgCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ursprüngliches Enddatum.
        /// </summary>
        internal static string OriginalEndDate {
            get {
                return ResourceManager.GetString("OriginalEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_ Passwort.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Bitte fahren Sie mit der Anmeldung fort.
        /// </summary>
        internal static string Please_Continue_to_login {
            get {
                return ResourceManager.GetString("Please Continue to login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Bitte geben Sie gültige Anmeldeinformationen ein.
        /// </summary>
        internal static string Please_enter_valid_Credentials {
            get {
                return ResourceManager.GetString("Please enter valid Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_ Bitte wählen Sie ein zukünftiges Datum.
        /// </summary>
        internal static string Please_select_a_future_date {
            get {
                return ResourceManager.GetString("Please select a future date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Priorität.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Speichern.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_E-Mail senden.
        /// </summary>
        internal static string Send_Email {
            get {
                return ResourceManager.GetString("Send Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_ Ein neues Passwort festlegen..
        /// </summary>
        internal static string set_a_new_password_ {
            get {
                return ResourceManager.GetString("set a new password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Anmelden.
        /// </summary>
        internal static string Sign_in {
            get {
                return ResourceManager.GetString("Sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Aufgaben erledigt.
        /// </summary>
        internal static string tasks_completed {
            get {
                return ResourceManager.GetString("tasks completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Diese Woche.
        /// </summary>
        internal static string This_Week {
            get {
                return ResourceManager.GetString("This Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Titel.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Aktualisierte Anheftungsstatus.
        /// </summary>
        internal static string UpdatedIsPinnedStatus {
            get {
                return ResourceManager.GetString("UpdatedIsPinnedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Dringend.
        /// </summary>
        internal static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Verwenden Sie weniger Worte im Titel oder in der Beschreibung.
        /// </summary>
        internal static string Use_Less_words_in_Title_or_Description {
            get {
                return ResourceManager.GetString("Use Less words in Title or Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Benutzerprofil.
        /// </summary>
        internal static string User_Profile {
            get {
                return ResourceManager.GetString("User Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Benutzername.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Bestätigungscode.
        /// </summary>
        internal static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Möchten tun.
        /// </summary>
        internal static string WantToDo {
            get {
                return ResourceManager.GetString("WantToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Wir senden Ihnen den Link zur Änderung des Passworts an die unten eingegebene E-Mail-Adresse.
        /// </summary>
        internal static string We_will_send_you_the_link_to_the_Email_which_you_have_entered_below_to_change_the_password {
            get {
                return ResourceManager.GetString("We will send you the link to the Email which you have entered below to change the" +
                        " password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Willkommen.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Willkommen bei Discipli.
        /// </summary>
        internal static string WelcomeToDiscipli {
            get {
                return ResourceManager.GetString("WelcomeToDiscipli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Willkommens-Initialisierungserklärung.
        /// </summary>
        internal static string WelcomInitialSetUpExplainer {
            get {
                return ResourceManager.GetString("WelcomInitialSetUpExplainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Arbeitsauftrag nicht gefunden.
        /// </summary>
        internal static string WorkItemNotFound {
            get {
                return ResourceManager.GetString("WorkItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Sie können jetzt das Passwort ändern und sich mit dem neuen Passwort anmelden..
        /// </summary>
        internal static string You_can_now_change_the_password_and_login_with_the_new_password {
            get {
                return ResourceManager.GetString("You can now change the password and login with the new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Sie können nur 3 Arbeitsaufträge anheften..
        /// </summary>
        internal static string YouCanOnlyPin3WorkItems {
            get {
                return ResourceManager.GetString("YouCanOnlyPin3WorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_Ihr Passwort wurde aktualisiert. Sie können sich jetzt mit dem neuen Passwort anmelden.
        /// </summary>
        internal static string Your_password_has_updated__you_can_now_login_with_the_new_password {
            get {
                return ResourceManager.GetString("Your password has updated, you can now login with the new password", resourceCulture);
            }
        }
    }
}
